grupos/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('grupos.views',
	url(r'^novo/$', 'grupo_create', name='grupo_create'),
	url(r'^lista/$','grupo_lista', name='grupo_lista'),
)

turismo/colaboradores/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('turismo.colaboradores.views',
    url(r'^novo/$', 'colaborador_create', name='colaborador_create'),
    url(r'^editar/(?P<colaborador_id>\d+)/$', 'colaborador_edit', name='colaborador_edit'),
    url(r'^lista/$','colaborador_lista', name='colaborador_lista'),
    
    url(r'^upload_picture/$', 'upload_picture', name='upload_picture'),
    url(r'^save_uploaded_picture/$', 'save_uploaded_picture', name='save_uploaded_picture'),
)

turismo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'turismo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'turismo.core.views.home', name='home'),
    url(r'^destinos/',include('turismo.destinos.urls', namespace='destinos')),
    url(r'^grupos/',include('turismo.grupos.urls', namespace='grupos')),
    url(r'^clientes/',include('turismo.clientes.urls',namespace='clientes')),
    url(r'^colaboradores/',include('turismo.colaboradores.urls',namespace='colaboradores')),
    url(r'^servicos/',include('turismo.servicos.urls',namespace='servicos')),

)

turismo/colaboradores/models.py
#coding: utf-8
from django.db import models
from turismo.destinos.models import Destino
from turismo.servicos.models import Servico
# Create your models here.

PESSOA = (
        ('J', 'Pessoa Jurídica'),
        ('F', 'Física'),
        )

class Colaborador(models.Model):
	nome = models.CharField(max_length=100)
	destino = models.ForeignKey(Destino)
	telefone = models.CharField(max_length=15)
	telefone2 = models.CharField(max_length=15,blank=True)
	email = models.CharField(max_length=30,blank=True)
	site = models.CharField(max_length=30,blank=True)
	servicos = models.ManyToManyField(Servico,verbose_name="Serviços")
	observacao = models.CharField(max_length=100,blank=True)
	def __unicode__(self):
	    return unicode(self.nome)

turismo/colaboradores/forms.py
# coding: utf-8

from django import forms
from turismo.colaboradores.models import Colaborador
from django.core.exceptions import ValidationError

class ColaboradorForm(forms.ModelForm):
    class Meta:
        model = Colaborador
        widgets = { 'servicos': forms.CheckboxSelectMultiple(attrs={'class':'form-inline'}),}

turismo/colaboradores/views.py
#coding: utf-8
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from turismo.colaboradores.forms import ColaboradorForm
from turismo.colaboradores.models import Colaborador
from django.conf import settings as django_settings

# Create your views here.

def colaborador_create(request):
    return render(request,'colaborador_novo.html')

def colaborador_create(request):
    form = ColaboradorForm(request.POST)
    if not form.is_valid():
        return render(request, 'colaborador_novo.html',{'form':form})
    obj = form.save()
    return HttpResponseRedirect("/colaboradores/lista/")

def colaborador_lista(request):
    return render(request, 'colaborador_lista.html',{'colaboradores':Colaborador.objects.all()})

def colaborador_edit(request,colaborador_id):
    colaborador = get_object_or_404(Colaborador,id=colaborador_id)
    if request.method == 'POST':
        return edit_colaborador(request,colaborador)
    else:
        return request_colaborador(request,colaborador)
def edit_colaborador(request,colaborador):
    form = ColaboradorForm(request.POST,instance=colaborador)
    if form.is_valid():
        colaborador = form.save(commit=False)
        colaborador.save()
        form.save_m2m()
        return HttpResponseRedirect('/colaboradores/lista')
    else:
        return render(request,'colaborador_editar.html',{'form':form})

def request_colaborador(request,colaborador):
    form = ColaboradorForm(instance=colaborador)
    return render(request,'colaborador_editar.html',{'form':form})


def upload_picture(request):
    profile_pictures = django_settings.MEDIA_ROOT + '/profile_pictures/'
    if not os.path.exists(profile_pictures):
        os.makedirs(profile_pictures)
    f = request.FILES['picture']
    filename = profile_pictures + request.user.username + '_tmp.jpg'
    with open(filename, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)    
    im = Image.open(filename)
    width, height = im.size
    if width > 350:
        new_width = 350
        new_height = (height * 350) / width
        new_size = new_width, new_height
        im.thumbnail(new_size, Image.ANTIALIAS)
        im.save(filename)
    return redirect('/colaboradores/?upload_picture=uploaded')

def save_uploaded_picture(request):
    try:
        x = int(request.POST.get('x'))
        y = int(request.POST.get('y'))
        w = int(request.POST.get('w'))
        h = int(request.POST.get('h'))
        tmp_filename = django_settings.MEDIA_ROOT + '/profile_pictures/' + request.user.username + '_tmp.jpg'
        filename = django_settings.MEDIA_ROOT + '/profile_pictures/' + request.user.username + '.jpg'
        im = Image.open(tmp_filename)
        cropped_im = im.crop((x, y, w+x, h+y))
        cropped_im.thumbnail((200, 200), Image.ANTIALIAS)
        cropped_im.save(filename)
        os.remove(tmp_filename)
    except Exception, e:
        pass
    return redirect('/colaboradores/')

turismo/colaboradores/templates/colaborador_editar.html
{% extends 'base.html' %}
{%block content%}

<form class="form-inline" method="POST" >
    {% csrf_token %}            
    <p><label>{{form.as_p}}</label></p>
    <p><button type="submit" class="btn btn-success">Salvar</button></p>
</form> 
{%endblock%}

turismo/colaboradores/templates/colaborador_lista.html
{% extends 'base.html' %}
{%block content%}
<a class="btn btn-warning" href="{% url 'colaboradores:colaborador_create' %}">Novo</a>
<table class="table">
    <thead>
        <tr>
            <th>Editar</th>
            <th>Nome</th>
        </tr>
    </thead>
    <tbody>
        {%for c in colaboradores%}
            <tr>
                <td class="a-table">
                <a href="{% url 'colaboradores:colaborador_edit' colaborador_id=c.id %}">Editar</a></td>
                <td>{{c.nome}}</td>
            </tr>
        {%endfor%}
    </tbody>
</table>


{%endblock%}

turismo/colaboradores/templates/colaborador_novo.html
{% extends 'base.html' %}
{%block content%}

<link href="{{ STATIC_URL }}css/jquery.Jcrop.min.css" rel="stylesheet">
<link href="{{ STATIC_URL }}css/principal" rel="stylesheet">
<script src="{{ STATIC_URL }}js/jquery.Jcrop.min.js"></script>
<script src="{{ STATIC_URL }}js/picture.js"></script>

<form class="form-inline" method="POST" >
    {% csrf_token %}            
    {{form.as_p}}
    <p><button type="submit" class="btn btn-success">Salvar</button></p>
</form> 


<!--

<form enctype="multipart/form-data" method="post" action="{% url 'colaboradores:upload_picture' %}" id="picture-upload-form">
    {% csrf_token %}
    <input type="file" name="picture" style="display: none">
    <button type="button" class="btn btn-default" id="btn-upload-picture">Upload new picture</button>
</form>


{% if uploaded_picture %}
        <form method="post" action="{% url 'colaboradores:save_uploaded_picture' %}">
          {% csrf_token %}
          <div class="modal fade" id="modal-upload-picture">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title">Crop Picture</h4>
                </div>
                <div class="modal-body">
                  <div class="selected-picture">
                    <p>Crop the profile picture and then click on the <strong>Save Picture</strong> button</p>
                    <img src="{{ MEDIA_URL }}profile_pictures/{{ user.username }}_tmp.jpg?_={% now 'U' %}" id="crop-picture">
                    <input type="hidden" id="x" name="x" />
                    <input type="hidden" id="y" name="y" />
                    <input type="hidden" id="w" name="w" />
                    <input type="hidden" id="h" name="h" />
                  </div>
                  <script type="text/javascript">
                    $(function () {
                      $("#modal-upload-picture").modal();
                      window.history.pushState("", "", "/settings/picture/");
                    });
                  </script>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
              </div>
            </div>
          </div>
        </form>
      {% endif %}

      --> 
{%endblock%}