destinos/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('destinos.views',
	url(r'^novo/$', 'destino_create', name='destino_create'),
	url(r'^editar/(?P<destino_id>\d+)/$', 'destino_edit', name='destino_edit'),
	url(r'^lista/$','destino_lista', name='destino_lista'),
)

grupos/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('grupos.views',
	url(r'^novo/$', 'grupo_create', name='grupo_create'),
	url(r'^lista/$','grupo_lista', name='grupo_lista'),
)

turismo/clientes/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('turismo.clientes.views',
    url(r'^novo/$', 'cliente_create', name='cliente_create'),
    url(r'^editar/(?P<cliente_id>\d+)/$', 'cliente_edit', name='cliente_edit'),
    url(r'^lista/$','cliente_lista', name='cliente_lista'),
    url(r'^relatorio/(?P<cliente_id>\d+)/$', 'relatorio_cliente', name='relatorio_cliente'),
)

turismo/colaboradores/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('turismo.colaboradores.views',
    url(r'^novo/$', 'colaborador_create', name='colaborador_create'),
    url(r'^editar/(?P<colaborador_id>\d+)/$', 'colaborador_edit', name='colaborador_edit'),
    url(r'^lista/$','colaborador_lista', name='colaborador_lista'),
    
    url(r'^upload_picture/$', 'upload_picture', name='upload_picture'),
    url(r'^save_uploaded_picture/$', 'save_uploaded_picture', name='save_uploaded_picture'),
)

turismo/servicos/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('turismo.servicos.views',
    url(r'^novo/$', 'servico_create', name='servico_create'),
    url(r'^editar/(?P<servico_id>\d+)/$', 'servico_edit', name='servico_edit'),
    url(r'^lista/$','servico_lista', name='servico_lista'),
)

turismo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'turismo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'turismo.core.views.home', name='home'),
    url(r'^destinos/',include('turismo.destinos.urls', namespace='destinos')),
    url(r'^grupos/',include('turismo.grupos.urls', namespace='grupos')),
    url(r'^clientes/',include('turismo.clientes.urls',namespace='clientes')),
    url(r'^colaboradores/',include('turismo.colaboradores.urls',namespace='colaboradores')),
    url(r'^servicos/',include('turismo.servicos.urls',namespace='servicos')),

)

turismo/core/models.py
from django.db import models

# Create your models here.

turismo/core/views.py
#coding:utf-8
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse as r

def home(request):
	return render(request, 'base.html')

turismo/core/templates/base.html
<html>
<head>
    <title>Turismo</title>
    
    <link rel="shortcut icon" href="../favicon.ico">
    <link href="{{ STATIC_URL }}css/default.css" rel="stylesheet" type="text/css"  />
    <link href="{{ STATIC_URL }}css/form_padrao.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/base.css" />
    <link href="{{ STATIC_URL }}css/datepicker.css" rel="stylesheet" type="text/css"  />


    <script src="{{ STATIC_URL }}js/jquery-latest.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-2.0.0.min.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>        
    <script src="{{ STATIC_URL }}js/jquery-ui-1.10.2.min.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>
    <script src="{{ STATIC_URL }}js/locales/bootstrap-datepicker.pt-BR.js"></script>
    
</head>
<body>
		<div class="container">
			<header class="clearfix">
				<h1>Turismo</h1>
			</header>
            <hr size="5" noshade align="right" style="background:black; margin-top:-30px;"/>
            <nav class="menu" id="cbp-spmenu-s1">
			    <h3>Menu</h3>
			   	<a href="{% url 'destinos:destino_lista' %}">Destinos</a>
                <a href="{% url 'grupos:grupo_lista' %}">Grupos</a>
                <a href="{% url 'clientes:cliente_lista' %}">Clientes</a>
                <a href="{% url 'colaboradores:colaborador_lista' %}">Colaboradores</a>
                <a href="{% url 'servicos:servico_lista' %}">Serviços</a>
		    </nav>
		</div>
        <div id="centro">
            {%block content%}
    		{%endblock%}	
        </div>

    	<script src="{{ STATIC_URL }}js/classie.js" type="text/javascript"></script>


<script type="text/javascript">

        $(document).ready(

            function(){

        {%block jquery%}
        {%endblock%}

        });
    </script>
</body>

    

</html>