grupos/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('grupos.views',
	url(r'^novo/$', 'grupo_create', name='grupo_create'),
	url(r'^lista/$','grupo_lista', name='grupo_lista'),
)

turismo/colaboradores/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('turismo.colaboradores.views',
    url(r'^novo/$', 'colaborador_create', name='colaborador_create'),
    url(r'^editar/(?P<colaborador_id>\d+)/$', 'colaborador_edit', name='colaborador_edit'),
    url(r'^lista/$','colaborador_lista', name='colaborador_lista'),
    
    url(r'^upload_picture/$', 'upload_picture', name='upload_picture'),
    url(r'^save_uploaded_picture/$', 'save_uploaded_picture', name='save_uploaded_picture'),
)

turismo/grupos/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('turismo.grupos.views',
	url(r'^novo/$', 'grupo_create', name='grupo_create'),
    url(r'^editar/(?P<grupo_id>\d+)/$','grupo_edit', name='grupo_edit'),
	url(r'^lista/$','grupo_lista', name='grupo_lista'),
    url(r'^inserir_ao_grupo/(?P<grupo_id>\d+)/(?P<cliente_id>\d+)/$','inserir_ao_grupo', name='inserir_ao_grupo'),
    url(r'^remover_do_grupo/(?P<grupo_id>\d+)/(?P<cliente_id>\d+)/$','remover_do_grupo', name='remover_do_grupo'),
    
    url(r'^clientes_fora/(?P<grupo_id>\d+)/$','clientes_fora', name='clientes_fora'),
    url(r'^clientes/(?P<grupo_id>\d+)/$','clientes_grupo', name='clientes_grupo'),
    url(r'^contrato/(?P<grupo_id>\d+)/(?P<cliente_id>\d+)/$','cliente_contrato', name='cliente_contrato'),
    url(r'^add_grupo/$','add_grupo', name='add_grupo'),
    url(r'^rm_grupo/$','rm_grupo', name='rm_grupo'),

    url(r'^colaboradores/(?P<grupo_id>\d+)/$','colaboradores_grupo', name='colaboradores_grupo'),
    url(r'^add_colaborador_grupo/$','add_colaborador_grupo', name='add_colaborador_grupo'),
    url(r'^rm_colaborador_grupo/$','rm_colaborador_grupo', name='rm_colaborador_grupo'),

    url(r'^roteiros/(?P<grupo_id>\d+)/$','roteiro_create', name='roteiro_create'),
    url(r'^roteiros/lista/(?P<grupo_id>\d+)/$','roteiro_lista', name='roteiro_lista'),
    url(r'^roteiros/(?P<roteiro_id>\d+)$','roteiro_edit', name='roteiro_edit'),
    
    url(r'^relatorios/(?P<grupo_id>\d+)/$','relatorio_grupo', name='relatorio_grupo'),
    url(r'^relatorios/1/(?P<grupo_id>\d+)/$','relatorio_clientes_telefone', name='relatorio_clientes_telefone'),
    url(r'^relatorios/2/(?P<grupo_id>\d+)/$','relatorio_clientes_rg', name='relatorio_clientes_rg'),
)

turismo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'turismo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'turismo.core.views.home', name='home'),
    url(r'^destinos/',include('turismo.destinos.urls', namespace='destinos')),
    url(r'^grupos/',include('turismo.grupos.urls', namespace='grupos')),
    url(r'^clientes/',include('turismo.clientes.urls',namespace='clientes')),
    url(r'^colaboradores/',include('turismo.colaboradores.urls',namespace='colaboradores')),
    url(r'^servicos/',include('turismo.servicos.urls',namespace='servicos')),

)

grupos/models.py
#coding: utf-8
from django.db import models

# Create your models here.

class Grupo(models.Model):
	name = models.CharField(max_length=100)
	destino = models.CharField(max_length=100)
	#destino = models.IntegerField()

turismo/grupos/models.py
#coding: utf-8
from django.db import models
from turismo.destinos.models import Destino
from turismo.clientes.models import Cliente
from turismo.colaboradores.models import Colaborador
# Create your models here.


SITUACAO = (
        ('A', 'Em Aberto'),
        ('B', 'Concluído'),
        ('C', 'Cancelado'),
        )

class Grupo(models.Model):
    nome = models.CharField(max_length=100)
    destino = models.ForeignKey(Destino)
    partida = models.CharField(max_length=10)
    chegada = models.CharField(max_length=10)
    numpessoas = models.IntegerField()
    situacao = models.CharField(max_length=1,choices=SITUACAO)
    clientes = models.ManyToManyField(Cliente,verbose_name="Pessoas Listadas", blank=True)
    valor_pessoa = models.DecimalField(default=0.0,max_digits=5,decimal_places=2)
    colaboradores = models.ManyToManyField(Colaborador,verbose_name="Colaboradores", blank=True)

class Roteiro(models.Model):
    titulo = models.CharField(max_length=50)
    descricao = models.CharField(max_length=500)
    grupo = models.ForeignKey(Grupo,null=True,blank=True)

grupos/forms.py
# coding: utf-8

from django import forms
from grupos.models import Grupo
from django.core.exceptions import ValidationError

class GrupoForm(forms.ModelForm):
    class Meta:
        model = Grupo

turismo/colaboradores/forms.py
# coding: utf-8

from django import forms
from turismo.colaboradores.models import Colaborador
from django.core.exceptions import ValidationError

class ColaboradorForm(forms.ModelForm):
    class Meta:
        model = Colaborador
        widgets = { 'servicos': forms.CheckboxSelectMultiple(attrs={'class':'form-inline'}),}

turismo/grupos/forms.py
# coding: utf-8

from django import forms
from turismo.grupos.models import Grupo,Roteiro
from django.core.exceptions import ValidationError
from django.forms.widgets import Select,CheckboxSelectMultiple

class GrupoForm(forms.ModelForm):
    class Meta:
        model = Grupo
        
        widgets = { 'clientes': forms.CheckboxSelectMultiple(attrs={'class':'checkbox'}),}

class RoteiroForm(forms.ModelForm):
	class Meta:
		model = Roteiro
		widgets = {
            'descricao': forms.Textarea(attrs={'cols': 200, 'rows': 5}),
        }

grupos/views.py
#coding: utf-8
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from grupos.forms import GrupoForm
from grupos.models import Grupo
from destinos.models import Destino
# Create your views here.

def grupo_create(request):
	return render(request,'grupo_novo.html')

def grupo_create(request):

	form = GrupoForm(request.POST)
	
	#print form.is_valid()

	if not form.is_valid():

		#if request.POST:
		#	raise Exception(form)
		#	raise Exception(request.POST)

		return render(request, 'grupo_novo.html',{'form': form, 'destinos':Destino.objects.all()})
	obj = form.save()
	return HttpResponseRedirect("/grupos/lista/")

def grupo_lista(request):
	return render(request, 'grupo_lista.html',{'grupos':Grupo.objects.all()})

turismo/colaboradores/views.py
#coding: utf-8
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from turismo.colaboradores.forms import ColaboradorForm
from turismo.colaboradores.models import Colaborador
from django.conf import settings as django_settings

# Create your views here.

def colaborador_create(request):
    return render(request,'colaborador_novo.html')

def colaborador_create(request):
    form = ColaboradorForm(request.POST)
    if not form.is_valid():
        return render(request, 'colaborador_novo.html',{'form':form})
    obj = form.save()
    return HttpResponseRedirect("/colaboradores/lista/")

def colaborador_lista(request):
    return render(request, 'colaborador_lista.html',{'colaboradores':Colaborador.objects.all()})

def colaborador_edit(request,colaborador_id):
    colaborador = get_object_or_404(Colaborador,id=colaborador_id)
    if request.method == 'POST':
        return edit_colaborador(request,colaborador)
    else:
        return request_colaborador(request,colaborador)
def edit_colaborador(request,colaborador):
    form = ColaboradorForm(request.POST,instance=colaborador)
    if form.is_valid():
        colaborador = form.save(commit=False)
        colaborador.save()
        form.save_m2m()
        return HttpResponseRedirect('/colaboradores/lista')
    else:
        return render(request,'colaborador_editar.html',{'form':form})

def request_colaborador(request,colaborador):
    form = ColaboradorForm(instance=colaborador)
    return render(request,'colaborador_editar.html',{'form':form})


def upload_picture(request):
    profile_pictures = django_settings.MEDIA_ROOT + '/profile_pictures/'
    if not os.path.exists(profile_pictures):
        os.makedirs(profile_pictures)
    f = request.FILES['picture']
    filename = profile_pictures + request.user.username + '_tmp.jpg'
    with open(filename, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)    
    im = Image.open(filename)
    width, height = im.size
    if width > 350:
        new_width = 350
        new_height = (height * 350) / width
        new_size = new_width, new_height
        im.thumbnail(new_size, Image.ANTIALIAS)
        im.save(filename)
    return redirect('/colaboradores/?upload_picture=uploaded')

def save_uploaded_picture(request):
    try:
        x = int(request.POST.get('x'))
        y = int(request.POST.get('y'))
        w = int(request.POST.get('w'))
        h = int(request.POST.get('h'))
        tmp_filename = django_settings.MEDIA_ROOT + '/profile_pictures/' + request.user.username + '_tmp.jpg'
        filename = django_settings.MEDIA_ROOT + '/profile_pictures/' + request.user.username + '.jpg'
        im = Image.open(tmp_filename)
        cropped_im = im.crop((x, y, w+x, h+y))
        cropped_im.thumbnail((200, 200), Image.ANTIALIAS)
        cropped_im.save(filename)
        os.remove(tmp_filename)
    except Exception, e:
        pass
    return redirect('/colaboradores/')

turismo/grupos/views.py
#coding: utf-8
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from turismo.grupos.forms import GrupoForm,RoteiroForm
from turismo.grupos.models import Grupo,Roteiro
from django.core.urlresolvers import reverse as r

from turismo.clientes.models import Cliente
from turismo.colaboradores.models import Colaborador
# Create your views here.

def grupo_create(request):
	form = GrupoForm(request.POST)
	if not form.is_valid():
		return render(request, 'grupo_novo.html', {'form': form})
	obj = form.save()
	return HttpResponseRedirect("/grupos/lista/")

def grupo_lista(request):
	return render(request, 'grupo_lista.html',{'grupos':Grupo.objects.all()})



def grupo_edit(request,grupo_id):

    grupo = get_object_or_404(Grupo,id=grupo_id)
    if request.method == 'POST':
        return edit_grupo(request,grupo)
    else:
        return request_grupo(request,grupo)

def edit_grupo(request,grupo):
    '''
        @edit_funcao: View para alterar os dados de um funcao
    '''
    form = GrupoForm(request.POST,instance=grupo)
    if form.is_valid():
        grupo = form.save(commit=False)
        grupo.save()
        return HttpResponseRedirect('/grupos/lista')
    else:
        return render(request,'grupo_editar.html',{'form':form})

def request_grupo(request,grupo):
    '''
        @request_funcao: View para obter os dados de um determinado funcao
    '''
    form = GrupoForm(instance=grupo)
    return render(request, 'grupo_editar.html',
        {'form':form,'grupo':grupo})

def inserir_ao_grupo(request,grupo_id,cliente_id):
    cliente = get_object_or_404(Cliente,id=cliente_id)
    grupo = get_object_or_404(Grupo,id=grupo_id)
    grupo.clientes.add(cliente)
    return HttpResponseRedirect(r('grupos:grupo_edit', args=[grupo.id]))
    #return HttpResponseRedirect(r('grupos:pessoas_grupo', args=[grupo.id]))

def remover_do_grupo(request,grupo_id,cliente_id):
    cliente = get_object_or_404(Cliente,id=cliente_id)
    grupo = get_object_or_404(Grupo,id=grupo_id)
    grupo.clientes.remove(cliente)
    return HttpResponseRedirect(r('grupos:grupo_edit', args=[grupo.id]))
    #return HttpResponseRedirect(r('grupos:pessoas_grupo', args=[grupo.id]))

def add_grupo(request):
    if request.is_ajax() and request.POST :
        # do some stuff        
        grupo = Grupo.objects.get(id=request.POST['grupo_id'])
        cliente = Cliente.objects.get(id=request.POST['cliente_id'])
        grupo.clientes.add(cliente)
        form = GrupoForm(instance=grupo)
        return render(request, 'pessoa_contrato.html',
            {'form':form,'grupo':grupo,'cliente':cliente})
    else:
        raise Http404r('grupos:grupo_edit', args=[grupo.id])
def rm_grupo(request):
    if request.is_ajax() and request.POST :
        # do some stuff        
        grupo = Grupo.objects.get(id=request.POST['grupo_id'])
        cliente = Cliente.objects.get(id=request.POST['cliente_id'])
        grupo.clientes.remove(cliente)
        form = GrupoForm(instance=grupo)
        return render(request, 'pessoas_dentro.html',
            {'form':form,'grupo':grupo,'clientes_dentro':grupo.clientes.all()})
    else:
        raise Http404

def clientes_fora(request,grupo_id):
    grupo = get_object_or_404(Grupo,id=grupo_id)
    return render(request, 'pessoas_fora.html',
       {'grupo':grupo,'clientes_fora':Cliente.objects.all().exclude(id__in=grupo.clientes.all())})

def clientes_grupo(request,grupo_id):
    grupo = get_object_or_404(Grupo,id=grupo_id)
    #return HttpResponseRedirect("/grupos/clientes/"+str(grupo.id)
    return render(request, 'pessoas_dentro.html',
       {'grupo':grupo,'clientes_dentro':grupo.clientes.all(),})

def cliente_contrato(request,cliente_id,grupo_id):
    pass


def add_colaborador_grupo(request):
    if request.is_ajax() and request.POST :
        # do some stuff        
        grupo = Grupo.objects.get(id=request.POST['grupo_id'])
        colaborador = Colaborador.objects.get(id=request.POST['colaborador_id'])
        grupo.colaboradores.add(colaborador)
        form = GrupoForm(instance=grupo)
        return render(request, 'colaboradores.html',
            {'form':form,'grupo':grupo,
            'colaboradores_dentro':grupo.colaboradores.all(),
            'colaboradores_fora':Colaborador.objects.all().exclude(id__in=grupo.colaboradores.all())})
    else:
        raise Http404r('grupos:grupo_edit', args=[grupo.id])

def rm_colaborador_grupo(request):
    if request.is_ajax() and request.POST :
        # do some stuff        
        grupo = Grupo.objects.get(id=request.POST['grupo_id'])
        colaborador = Colaborador.objects.get(id=request.POST['colaborador_id'])
        grupo.colaboradores.remove(colaborador)
        
        form = GrupoForm(instance=grupo)
        return render(request, 'colaboradores.html',
            {'form':form,'grupo':grupo,
            'colaboradores_dentro':grupo.colaboradores.all(),
            'colaboradores_fora':Colaborador.objects.all().exclude(id__in=grupo.colaboradores.all())})
    else:
        raise Http404
        
def colaboradores_grupo(request,grupo_id):
    grupo = get_object_or_404(Grupo,id=grupo_id)
    return render(request, 'colaboradores.html',
        {'grupo':grupo,
        'colaboradores_dentro':grupo.colaboradores.all(),
        'colaboradores_fora':Colaborador.objects.all().exclude(id__in=grupo.colaboradores.all())})

def roteiro_lista(request,grupo_id):
    grupo = get_object_or_404(Grupo,id=grupo_id)
    return render(request,'roteiros.html',{'grupo':grupo,'roteiros':Roteiro.objects.filter(grupo=grupo)})

def roteiro_create(request,grupo_id):
    grupo = get_object_or_404(Grupo,id=grupo_id)
    if request.method == 'POST':
        form = RoteiroForm(request.POST)
        if not form.is_valid():
            return render(request, 'roteiros.html', {'form': form,'roteiros':Roteiro.objects.filter(grupo=grupo)})
        obj = form.save()
        obj.grupo = grupo
        obj.save()
        return render(request,'roteiros.html',{'grupo':grupo,'roteiros':Roteiro.objects.filter(grupo=grupo)})
    form = RoteiroForm()
    return render(request, 'roteiro_novo.html', {'grupo':grupo,'form': form,'roteiros':Roteiro.objects.filter(grupo=grupo)})

def roteiro_edit(request,roteiro_id):
    roteiro = get_object_or_404(Roteiro,id=roteiro_id)
    if request.method == 'POST':
        return edit_roteiro(request,roteiro)
    else:
        return request_roteiro(request,roteiro)

def edit_roteiro(request,roteiro):
    grupo = get_object_or_404(Grupo,id=roteiro.grupo.id)
    form = RoteiroForm(request.POST,instance=roteiro)
    if form.is_valid():
        roteiro = form.save(commit=False)
        roteiro.grupo = grupo
        roteiro.save()
        return render(request, 'roteiros.html', {'grupo':grupo,'form': RoteiroForm(),'roteiros':Roteiro.objects.filter(grupo=grupo)})

    else:
        return render(request,'roteiro_editar.html',{'form':form})

def request_roteiro(request,roteiro):
    form = RoteiroForm(instance=roteiro)
    return render(request, 'roteiro_editar.html',
        {'form':form,'roteiro':roteiro})


def relatorio_grupo(request,grupo_id):
    grupo = get_object_or_404(Grupo,id=grupo_id)
    return render(request, 'relatorios_grupo.html',{'grupo':grupo})

def relatorio_clientes_telefone(request,grupo_id):
    grupo = get_object_or_404(Grupo,id=grupo_id)
    return render(request, 'relatorio_telefone.html',
        {'grupo':grupo,'clientes_dentro':grupo.clientes.all()})

def relatorio_clientes_rg(request,grupo_id):
    grupo = get_object_or_404(Grupo,id=grupo_id)
    return render(request, 'relatorio_rg.html',
        {'grupo':grupo,'clientes_dentro':grupo.clientes.all()})

turismo/grupos/templates/colaboradores.html
{% extends 'base.html' %}

{%block jquery%}
//Adicionando ao grupo

$(".add_grupo").click(function(e){
    e.preventDefault();
    $id_colaborador = this.id
    
    $.ajax({
        type:"POST",
        cache: false,
        url: "{% url 'grupos:add_colaborador_grupo' %}",
        data: {
        csrfmiddlewaretoken: "{{csrf_token}}",
        grupo_id: {{grupo.id}},
        colaborador_id: $id_colaborador,
    },
        
        success:function(data){
            $( "body" ).html(data);
        },
    error: function(rs, e){
        alert(rs);
},

    });
});


//Removendo disciplinas
$(".rm_grupo").click(function(e){
    e.preventDefault();
    $id_colaborador = this.id
    
    $.ajax({
        type:"POST",
        cache: false,
        url: "{% url 'grupos:rm_colaborador_grupo' %}",
        data: {
        csrfmiddlewaretoken: "{{csrf_token}}",
        grupo_id: {{grupo.id}},
        colaborador_id: $id_colaborador,
    },
        
        success:function(data){
            $( "body" ).html(data);
        },
    error: function(rs, e){
        alert(rs);
},

    });
});

{%endblock%}


{%block content%}
{%include 'menu_grupo.html'%}




            Colaboradores do grupo<br/>
            

           {% for d in colaboradores_dentro %}

            <form id="{{d.id}}" method='POST'>
                {%csrf_token%}
                <input class ="rm_grupo btn btn-success" type="submit" value='{{d.nome}}' id='{{d.id}}' style="width:100px"/>
            </form>

            {% endfor %}
            <br/>
            <!--
            Clientes que não estão no grupo<br/>
            {% for p in clientes_fora %}
              <a class="add_grupo btn btn-danger" href="{% url 'grupos:inserir_ao_grupo' grupo_id=grupo.id cliente_id=p.id %}"
              value='{{p.nome}}' id='{{p.id}}'>{{p}}</a><br/><br/>
            {% endfor %}-->
            {%for d in colaboradores_fora%}

            <form id="{{d.id}}" method='POST'>
                {%csrf_token%}
                <input class ="add_grupo btn btn-danger" type="submit" value='{{d.nome}}' id='{{d.id}}' style="width:100px"/>
            </form>
            {%endfor%}



{%endblock%}

turismo/grupos/templates/grupo_editar.html
{% extends 'base.html' %}


{%block content%}
{%include 'menu_grupo.html'%}


<h3>Editar</h3>


<form class="form-inline" method="POST" >

    {% csrf_token %}            
    <p><label>{{form.nome.label}} :</label>{{form.nome}}{{form.nome.erros}}</p>
    <p><label>{{form.destino.label}} :</label>{{form.destino}}{{form.destino.erros}}</p>
    <p><label>{{form.partida.label}} : </label>{{form.partida}}</p>
    <p><label>{{form.chegada.label}} : </label>{{form.chegada}}</p>
    <p><label>{{form.numpessoas.label}} : </label>{{form.numpessoas}}</p>
    <p><label>{{form.valor_pessoa.label}} : </label>{{form.valor_pessoa}}</p>
    <p><label>{{form.situacao.label}}</label>{{form.situacao}}</p>

<p><button type="submit" class="btn btn-success">Salvar</button></p>
 
 </form> 



 <script type="text/javascript">
    $('#id_partida').datepicker({
        autoclose: true,
        language: 'pt-BR',
        format: "dd/mm/yyyy"
    });

    $('#id_chegada').datepicker({
        autoclose: true,
        language: 'pt-BR',
        format: "dd/mm/yyyy"
    });
 </script>
{%endblock%}

turismo/grupos/templates/grupo_novo.html
{% extends 'base.html' %}
{%block content%}


<form class="form-inline" method="POST" >
	{% csrf_token %}			
	<p><label>{{form.nome.label}} :</label>{{form.nome}}</p>
	<p><label>{{form.destino.label}} :</label>{{form.destino}}</p>
	<p><label>{{form.partida.label}} : </label>{{form.partida}}</p>
	<p><label>{{form.chegada.label}} : </label>{{form.chegada}}</p>
	<p><label>{{form.numpessoas.label}} : </label>{{form.numpessoas}}</p>
    <p><label>{{form.valor_pessoa.label}} : </label>{{form.valor_pessoa}}</p>
    <p><label>{{form.situacao.label}}</label>{{form.situacao}}</p>	
	<p><button type="submit" class="btn btn-success">Salvar</button></p>
</form>	

 <script type="text/javascript">
    $('#id_partida').datepicker({
        autoclose: true,
        language: 'pt-BR',
        format: "dd/mm/yyyy"
    });

    $('#id_chegada').datepicker({
        autoclose: true,
        language: 'pt-BR',
        format: "dd/mm/yyyy"
    });
 </script>
{%endblock%}

turismo/grupos/templates/menu_grupo.html
    <ul class="nav nav-pills">
      <a class="btn btn-primary" href="{% url 'grupos:grupo_edit' grupo_id=grupo.id %}">Dados do grupo</a>
      <a class="btn btn-warning" href="{% url 'grupos:clientes_fora' grupo_id=grupo.id%}">Clientes fora do grupo</a>

      <a class="btn btn-success" href="{% url 'grupos:clientes_grupo' grupo_id=grupo.id%}">Clientes do grupo</a>
      <a class="btn" href="{% url 'grupos:colaboradores_grupo' grupo_id=grupo.id %}">Colaboradores</a>
      <a class="btn btn-info" href="{% url 'grupos:roteiro_lista' grupo_id=grupo.id%}">Roteiro</a>
      <a class="btn btn-danger" href="#">Mensagem</a>
      <a class="btn btn-info" href="{% url 'grupos:relatorio_grupo' grupo_id=grupo.id%}">Relatórios</a>
      <a class="btn btn-danger" href="">Despesas</a>
    </ul>

turismo/grupos/templates/pessoas_dentro.html
{% extends 'base.html' %}

{%block jquery%}
//Adicionando ao grupo

$(".add_grupo").click(function(e){
    e.preventDefault();
    $id_cliente = this.id
    
    $.ajax({
        type:"POST",
        cache: false,
        url: "{% url 'grupos:add_grupo' %}",
        data: {
        csrfmiddlewaretoken: "{{csrf_token}}",
        grupo_id: {{grupo.id}},
        cliente_id: $id_cliente,
    },
        
        success:function(data){
            $( "body" ).html(data);
        },
    error: function(rs, e){
        alert(rs);
},

    });
});


//Removendo disciplinas
$(".rm_grupo").click(function(e){
    e.preventDefault();
    $id_cliente = this.id
    
    $.ajax({
        type:"POST",
        cache: false,
        url: "{% url 'grupos:rm_grupo' %}",
        data: {
        csrfmiddlewaretoken: "{{csrf_token}}",
        grupo_id: {{grupo.id}},
        cliente_id: $id_cliente,
    },
        
        success:function(data){
            $( "body" ).html(data);
        },
    error: function(rs, e){
        alert(rs);
},

    });
});

{%endblock%}


{%block content%}
{%include 'menu_grupo.html'%}


    <div class="bs-callout bs-callout-info">
      <h4>Clientes que não estão no grupo</h4>
    </div>

    <div class="panel-body">
          <div class="adv-table">
              <table class="table table-bordered table-striped" id="hidden-table-info">
                 <thead>
                <tr>
                    <th>Remover</th>
                    <th>Nome</th>
                </tr>
              </thead>
              <tbody>
              
                {% for d in clientes_dentro %}
                      <tr>
                        <td class="td-tam"> 
                          <form id="{{d.id}}" method='POST'>
                                  {%csrf_token%}
                                  <a class ="rm_grupo btn-link" id='{{d.id}}' style="width:100px">
                                  Remover</a>
                          </form>
                        </td>
                        <td>{{d.nome}}</td>
                      </tr>
                {%endfor%}
              
              </tbody>
              </table>

          </div>
    </div>

  <script src="{{ STATIC_URL }}js/jquery.dataTables.js" type="text/javascript" ></script>
  <script src="{{ STATIC_URL }}js/DT_bootstrap.js" type="text/javascript" ></script>

        <script type="text/javascript">
          /* Formating function for row details */

         $(document).ready(function() {
              var oTable = $('#hidden-table-info').dataTable( {
                  "aoColumnDefs": [
                      { "bSortable": false, "aTargets": [ 0 ] }
                  ],
                  "aaSorting": [[1, 'asc']]
              });

          } );
      </script>
{%endblock%}

turismo/grupos/templates/relatorios_grupo.html
{% extends 'base.html' %}
{%block content%}
{%include 'menu_grupo.html'%}

<div>
<h3>Relatório somente com o telefone</h3>
<a class="btn btn-info" href="{% url 'grupos:relatorio_clientes_telefone' grupo_id=grupo.id%}">Gerar</a>
</div>

<div>
<h3>Relatório com RG e Telefone</h3>
<a class="btn btn-info" href="{% url 'grupos:relatorio_clientes_rg' grupo_id=grupo.id%}">Gerar</a>
</div>




{%endblock%}