grupos/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('grupos.views',
	url(r'^novo/$', 'grupo_create', name='grupo_create'),
	url(r'^lista/$','grupo_lista', name='grupo_lista'),
)

turismo/clientes/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('turismo.clientes.views',
    url(r'^novo/$', 'cliente_create', name='cliente_create'),
    url(r'^editar/(?P<cliente_id>\d+)/$', 'cliente_edit', name='cliente_edit'),
    url(r'^lista/$','cliente_lista', name='cliente_lista'),
    url(r'^relatorio/(?P<cliente_id>\d+)/$', 'relatorio_cliente', name='relatorio_cliente'),
)

turismo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'turismo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'turismo.core.views.home', name='home'),
    url(r'^destinos/',include('turismo.destinos.urls', namespace='destinos')),
    url(r'^grupos/',include('turismo.grupos.urls', namespace='grupos')),
    url(r'^clientes/',include('turismo.clientes.urls',namespace='clientes')),
    url(r'^colaboradores/',include('turismo.colaboradores.urls',namespace='colaboradores')),
    url(r'^servicos/',include('turismo.servicos.urls',namespace='servicos')),

)

turismo/clientes/models.py
#coding: utf-8
from django.db import models

# Create your models here.

class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    nascimento = models.CharField(max_length=10)
    cpf = models.CharField(max_length=11)
    rg = models.CharField(max_length=20)
    orgao = models.CharField(max_length=20)
    endereco = models.CharField(max_length=30)
    bairro = models.CharField(max_length=20)
    cidade = models.CharField(max_length=20)
    estado = models.CharField(max_length=20)
    cep = models.CharField(max_length=10)
    tel01 = models.CharField(max_length=10)
    tel02 = models.CharField(max_length=10)
    email = models.EmailField(max_length=25)

    def __unicode__(self):
        return unicode(self.nome)

turismo/grupos/models.py
#coding: utf-8
from django.db import models
from turismo.destinos.models import Destino
from turismo.clientes.models import Cliente
from turismo.colaboradores.models import Colaborador
# Create your models here.


SITUACAO = (
        ('A', 'Em Aberto'),
        ('B', 'Concluído'),
        ('C', 'Cancelado'),
        )

class Grupo(models.Model):
    nome = models.CharField(max_length=100)
    destino = models.ForeignKey(Destino)
    partida = models.CharField(max_length=10)
    chegada = models.CharField(max_length=10)
    numpessoas = models.IntegerField()
    situacao = models.CharField(max_length=1,choices=SITUACAO)
    clientes = models.ManyToManyField(Cliente,verbose_name="Pessoas Listadas", blank=True)
    valor_pessoa = models.DecimalField(default=0.0,max_digits=5,decimal_places=2)
    colaboradores = models.ManyToManyField(Colaborador,verbose_name="Colaboradores", blank=True)

class Roteiro(models.Model):
    titulo = models.CharField(max_length=50)
    descricao = models.CharField(max_length=500)
    grupo = models.ForeignKey(Grupo,null=True,blank=True)

turismo/clientes/forms.py
# coding: utf-8

from django import forms
from turismo.clientes.models import Cliente
from django.core.exceptions import ValidationError

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente

turismo/clientes/views.py
#coding: utf-8
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from turismo.clientes.forms import ClienteForm
from turismo.clientes.models import Cliente
from turismo.grupos.models import Grupo

# Create your views here.

def cliente_create(request):
    return render(request,'cliente_novo.html')

def cliente_create(request):
    form = ClienteForm(request.POST)
    if not form.is_valid():
        return render(request, 'cliente_novo.html',{'form':form})
    obj = form.save()
    return HttpResponseRedirect("/clientes/lista/")

def cliente_lista(request):
    return render(request, 'cliente_lista.html',{'clientes':Cliente.objects.all()})

def cliente_edit(request,cliente_id):
    cliente = get_object_or_404(Cliente,id=cliente_id)
    if request.method == 'POST':
        return edit_grupo(request,cliente)
    else:
        return request_grupo(request,cliente)
def edit_grupo(request,cliente):
    form = ClienteForm(request.POST,instance=cliente)
    if form.is_valid():
        cliente = form.save(commit=False)
        cliente.save()
        return HttpResponseRedirect('/clientes/lista')
    else:
        return render(request,'cliente_editar.html',{'form':form})

def request_grupo(request,cliente):
    form = ClienteForm(instance=cliente)
    return render(request,'cliente_editar.html',{'form':form,'cliente':cliente})

def relatorio_cliente(request,cliente_id):
    cliente = get_object_or_404(Cliente,id=cliente_id)
    grupos = Grupo.objects.filter(clientes=cliente)
    return render(request,'imprimir_cadastro.html',{'cliente':cliente,'grupos':grupos})

turismo/clientes/templates/cliente_editar.html
{% extends 'base.html' %}
{%block content%}

<form class="form-inline" method="POST" >
    {% csrf_token %}            
    <p><label>{{form.nome.label}} :</label>{{form.nome}}</p>
    <p><label>{{form.nascimento.label}} :</label>{{form.nascimento}}</p>
    <p><label>{{form.cpf.label}}</label>{{form.cpf}}</p>
    <p><label>{{form.rg.label}}</label>{{form.rg}}</p>
    <p><label>{{form.orgao.label}}</label>{{form.orgao}}</p>
    <p><label>{{form.endereco.label}}</label>{{form.endereco}}</p>
    <p><label>{{form.bairro.label}}</label>{{form.bairro}}</p>
    <p><label>{{form.cidade.label}}</label>{{form.cidade}}</p>
    <p><label>{{form.estado.label}}</label>{{form.estado}}</p>
    <p><label>{{form.cep.label}}</label>{{form.cep}}</p>
    <p><label>{{form.tel01.label}}</label>{{form.tel01}}</p>
    <p><label>{{form.tel02.label}}</label>{{form.tel02}}</p>
    <p><label>{{form.email.label}}</label>{{form.email}}</p>

    <p><button type="submit" class="btn btn-success">Salvar</button></p>
</form> 
<a class="btn btn-info" href="{% url 'clientes:relatorio_cliente' cliente_id=cliente.id%}">Imprimir Cadastro</a

{%endblock%}

turismo/clientes/templates/cliente_lista.html
{% extends 'base.html' %}
{%block content%}
<a class="btn btn-warning" href="{% url 'clientes:cliente_create' %}">Novo</a>
<table class="table">
    <thead>
        <tr>
            <th>Editar</th>
            <th>Nome</th>
        </tr>
    </thead>
    <tbody>
        {%for c in clientes%}
            <tr>
                <td class="a-table">
                <a href="{% url 'clientes:cliente_edit' cliente_id=c.id %}">Editar</a></td>
                <td>{{c.nome}}</td>
            </tr>
        {%endfor%}
    </tbody>
</table>


{%endblock%}

turismo/clientes/templates/cliente_novo.html
{% extends 'base.html' %}
{%block content%}

<form class="form-inline" method="POST" >
    {% csrf_token %}            
    <p><label>{{form.nome.label}} :</label>{{form.nome}}</p>
    <p><label>{{form.nascimento.label}} :</label>{{form.nascimento}}</p>
    <p><label>{{form.cpf.label}}</label>{{form.cpf}}</p>
    <p><label>{{form.rg.label}}</label>{{form.rg}}</p>
    <p><label>{{form.orgao.label}}</label>{{form.orgao}}</p>
    <p><label>{{form.endereco.label}}</label>{{form.endereco}}</p>
    <p><label>{{form.bairro.label}}</label>{{form.bairro}}</p>
    <p><label>{{form.cidade.label}}</label>{{form.cidade}}</p>
    <p><label>{{form.estado.label}}</label>{{form.estado}}</p>
    <p><label>{{form.cep.label}}</label>{{form.cep}}</p>
    <p><label>{{form.tel01.label}}</label>{{form.tel01}}</p>
    <p><label>{{form.tel02.label}}</label>{{form.tel02}}</p>
    <p><label>{{form.email.label}}</label>{{form.email}}</p>

    <p><button type="submit" class="btn btn-success">Salvar</button></p>
</form> 

 <script type="text/javascript">
    $('#id_partida').datepicker({
        autoclose: true,
        language: 'pt-BR',
        format: "dd/mm/yyyy"
    });

    $('#id_chegada').datepicker({
        autoclose: true,
        language: 'pt-BR',
        format: "dd/mm/yyyy"
    });
 </script>
{%endblock%}

turismo/clientes/templates/imprimir_cadastro.html
<link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet" type="text/css" />
<link href="{{ STATIC_URL }}css/relatorio_cliente.css" rel="stylesheet" type="text/css" />
<script src="{{ STATIC_URL }}js/bootstrap.min.js" type="text/javascript"></script>

<div id="relatorio">

 <center><h2>Cadastro do cliente</h2></center>
<h4>
<div id="centro">
 <label>Nome: {{cliente.nome}}</label><br/>
 <label>Data de Nascimento:{{cliente.nascimento}}</label><br/>
 <label>CPF: {{cliente.cpf}}</label><br/>
 <label>RG: {{cliente.rg}}</label><br/>
 <label>Órgão Expedidor: {{cliente.orgao}}</label><br/>
 <label>Endereço: {{cliente.endereco}}</label><br/>
 <label>Bairro: {{cliente.bairro}}</label><br/>
 <label>Cidade: {{cliente.cidade}}</label><br/>
 <label>Estado: {{cliente.estado}}</label><br/>
 <label>CEP: {{cliente.cep}}</label><br/>
 <label>Telefone 01: {{cliente.tel01}}</label><br/>
 <label>Telefone 02: {{cliente.tel02}}</label><br/>
 <label>Email: {{cliente.email}}</label><br/>

 --------------------------------------------------------------------------------------------------------------------------------
  <center><h2>Histórico</h2></center>

  <table class="table">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Destino</th>
			<th>Partida</th>
			<th>Chegada</th>
		</tr>
	</thead>
	<tbody>
		{%for g in grupos%}
			<tr>
				<td>{{g.nome}}</td>
				<td>{{g.destino}}</td>
				<td>{{g.partida}}</td>
				<td>{{g.chegada}}</td>
			</tr>
		{%endfor%}
	</tbody>
</table>
 </div>

 </h4>

</div>